### ISSUE TITLE
Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by MrGecko** [chartes/erasmus#2]
**Use case:**
_lorsque je transcris un titre dans "transcription de la page de titre", et que je clique sur "contribuer", il apparaît dans la notice (jusqu'ici, tout va bien). Si je retourne sur cette notice (sous la rubrique "Informations complémentaires", bouton "Modifier"), les informations que je viens d'entrer disparaissent..._

**Log :**
[2018-07-09 09:28:52 +0200] [10071] [INFO] Starting gunicorn 19.8.1
[2018-07-09 09:28:52 +0200] [10071] [DEBUG] Arbiter booted
[2018-07-09 09:28:52 +0200] [10071] [INFO] Listening at: http://127.0.0.1:5020 (10071)
[2018-07-09 09:28:52 +0200] [10071] [INFO] Using worker: sync
[2018-07-09 09:28:52 +0200] [10074] [INFO] Booting worker with pid: 10074
[2018-07-09 09:28:52 +0200] [10076] [INFO] Booting worker with pid: 10076
[2018-07-09 09:28:52 +0200] [10078] [INFO] Booting worker with pid: 10078
[2018-07-09 09:28:52 +0200] [10071] [DEBUG] 3 workers
[2018-07-09 09:29:04 +0200] [10078] [DEBUG] GET /erasmus/
[2018-07-09 09:29:04 +0200] [10074] [DEBUG] GET /erasmus/statics/css/bootstrap.css
[2018-07-09 09:29:04 +0200] [10078] [DEBUG] GET /erasmus/statics/js/jquery.js
[2018-07-09 09:29:04 +0200] [10076] [DEBUG] GET /erasmus/statics/js/popper.js
[2018-07-09 09:29:04 +0200] [10078] [DEBUG] GET /erasmus/statics/js/bootstrap.js
[2018-07-09 09:29:04 +0200] [10074] [DEBUG] GET /erasmus/statics/images/erasmus1.jpeg
[2018-07-09 09:29:04 +0200] [10078] [DEBUG] GET /erasmus/statics/images/enc.jpeg
[2018-07-09 09:29:04 +0200] [10078] [DEBUG] GET /erasmus/statics/images/iuf.png
[2018-07-09 09:29:04 +0200] [10074] [DEBUG] GET /erasmus/statics/images/centre_jean_mabillon.png
[2018-07-10 23:21:33 +0200] [10078] [DEBUG] GET /erasmus/
[2018-07-10 23:21:33 +0200] [10078] [DEBUG] GET /erasmus/statics/css/bootstrap.css
[2018-07-10 23:21:33 +0200] [10078] [DEBUG] GET /erasmus/statics/js/jquery.js
[2018-07-10 23:21:33 +0200] [10078] [DEBUG] GET /erasmus/statics/js/popper.js
[2018-07-10 23:21:33 +0200] [10078] [DEBUG] GET /erasmus/statics/js/bootstrap.js
[2018-07-10 23:21:34 +0200] [10076] [DEBUG] GET /erasmus/statics/images/erasmus1.jpeg
[2018-07-10 23:21:34 +0200] [10078] [DEBUG] GET /erasmus/statics/images/iuf.png
[2018-07-10 23:21:34 +0200] [10074] [DEBUG] GET /erasmus/statics/images/enc.jpeg
[2018-07-10 23:21:34 +0200] [10078] [DEBUG] GET /erasmus/statics/images/centre_jean_mabillon.png
[2018-07-10 23:21:37 +0200] [10078] [DEBUG] GET /erasmus/connexion
[2018-07-10 23:21:37 +0200] [10078] [DEBUG] GET /erasmus/statics/css/bootstrap.css
[2018-07-10 23:21:47 +0200] [10078] [DEBUG] POST /erasmus/connexion
[2018-07-10 23:21:48 +0200] [10078] [DEBUG] GET /erasmus/
[2018-07-10 23:21:48 +0200] [10078] [DEBUG] GET /erasmus/statics/images/erasmus1.jpeg
[2018-07-10 23:21:48 +0200] [10078] [DEBUG] GET /erasmus/statics/images/enc.jpeg
[2018-07-10 23:22:02 +0200] [10074] [DEBUG] GET /erasmus/recherche_rapide
[2018-07-10 23:22:07 +0200] [10074] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:22:08 +0200] [10074] [DEBUG] GET /erasmus/statics/images/livre.jpeg
[2018-07-10 23:22:08 +0200] [10076] [DEBUG] GET /erasmus/statics/images/edit.png
[2018-07-10 23:22:08 +0200] [10078] [DEBUG] GET /erasmus/statics/images/erasmus.jpeg
[2018-07-10 23:22:08 +0200] [10074] [DEBUG] GET /erasmus/statics/images/trash.png
[2018-07-10 23:22:13 +0200] [10076] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:27:19 +0200] [10078] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:27:19 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:27:20 +0200] [10078] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:27:33 +0200] [10078] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:27:48 +0200] [10078] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:27:48 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:27:49 +0200] [10076] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:28:06 +0200] [10076] [DEBUG] GET /erasmus/exemplaire/7374
[2018-07-10 23:28:09 +0200] [10078] [DEBUG] GET /erasmus/suppression_exemplaire/7374
[2018-07-10 23:28:12 +0200] [10078] [DEBUG] POST /erasmus/suppression_exemplaire/7374
[2018-07-10 23:28:12 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:28:13 +0200] [10078] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:28:45 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/statics/css/bootstrap.css
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/statics/js/jquery.js
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/statics/js/popper.js
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/statics/js/bootstrap.js
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:28:46 +0200] [10076] [DEBUG] GET /erasmus/statics/images/livre.jpeg
[2018-07-10 23:28:46 +0200] [10078] [DEBUG] GET /erasmus/statics/images/edit.png
[2018-07-10 23:28:46 +0200] [10076] [DEBUG] GET /erasmus/statics/images/trash.png
[2018-07-10 23:28:59 +0200] [10074] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:29:06 +0200] [10078] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:29:06 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:29:07 +0200] [10074] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:29:14 +0200] [10074] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:29:26 +0200] [10076] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:29:26 +0200] [10074] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:29:26 +0200] [10074] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:29:31 +0200] [10076] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:29:46 +0200] [10076] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:29:47 +0200] [10074] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:29:47 +0200] [10074] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:30:01 +0200] [10078] [DEBUG] GET /erasmus/exemplaire/7375
[2018-07-10 23:30:04 +0200] [10074] [DEBUG] GET /erasmus/suppression_exemplaire/7375
[2018-07-10 23:30:06 +0200] [10074] [DEBUG] POST /erasmus/suppression_exemplaire/7375
[2018-07-10 23:30:06 +0200] [10074] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:30:07 +0200] [10074] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:30:18 +0200] [10078] [DEBUG] GET /erasmus/modif_edition/201899
[2018-07-10 23:30:36 +0200] [10074] [DEBUG] POST /erasmus/modif_edition/201899
[2018-07-10 23:30:36 +0200] [10078] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:30:36 +0200] [10076] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:30:51 +0200] [10076] [DEBUG] GET /erasmus/ajout_exemplaire/201899
[2018-07-10 23:31:12 +0200] [10076] [DEBUG] POST /erasmus/ajout_exemplaire/201899
[2018-07-10 23:31:12 +0200] [10076] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:31:13 +0200] [10076] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:31:23 +0200] [10074] [DEBUG] GET /erasmus/ajout_exemplaire/201899
[2018-07-10 23:31:54 +0200] [10076] [DEBUG] POST /erasmus/ajout_exemplaire/201899
[2018-07-10 23:31:54 +0200] [10076] [ERROR] Error handling request /erasmus/ajout_exemplaire/201899
Traceback (most recent call last):
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/webapp/erasmus/app/routes.py", line 402, in ajout_exemplaire
    return render_template("pages/ajout_exemplaire.html")
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/webapp/erasmus/app/templates/pages/ajout_exemplaire.html", line 1, in top-level template code
    {% extends "conteneur.html" %}
  File "/srv/webapp/erasmus/app/templates/conteneur.html", line 40, in top-level template code
    ({{ current_user.user_nom }})</a></li>
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 594, in get
    value = state._load_expired(state, passive)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 608, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 876, in load_scalar_attributes
    only_load_props=attribute_names)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 188, in load_on_ident
    identity_token=identity_token
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
    return q.one()
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2894, in one
    ret = self.one_or_none()
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2864, in one_or_none
    ret = list(self)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2935, in __iter__
    return self._execute_and_instances(context)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2956, in _execute_and_instances
    close_with_result=True)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2965, in _get_bind_args
    **kw
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2947, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/srv/webapp/erasmus/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. 
To begin a new transaction with this Session, first issue Session.rollback(). 
Original exception was: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`erasmus`.`exemplaire`, CONSTRAINT `fk_exemplaire_2` FOREIGN KEY (`exemplaire_bibliothecae_id`) REFERENCES `bibliothecae` (`bibliothecae_id`) ON DELETE CASCADE ON UPDATE CASCADE)') [SQL: 'INSERT INTO exemplaire (exemplaire_pressmark, exemplaire_hauteur, `exemplaire_variantesEdition`, `exemplaire_digitalURL`, exemplaire_notes, exemplaire_provenances, `exemplaire_locFingerprint`, `exemplaire_stcnFingerprint`, `exemplaire_annotationManuscrite`, `exemplaire_collator_etatMateriel`, exemplaire_collator_largeur, `exemplaire_reliure_recueilFactice`, exemplaire_reliure_reliure, `exemplaire_reliure_reliureXVI`, `exemplaire_relieAvec`, exemplaire_edition_id, exemplaire_user_id, exemplaire_bibliothecae_id) VALUES (%(exemplaire_pressmark)s, %(exemplaire_hauteur)s, %(exemplaire_variantesEdition)s, %(exemplaire_digitalURL)s, %(exemplaire_notes)s, %(exemplaire_provenances)s, %(exemplaire_locFingerprint)s, %(exemplaire_stcnFingerprint)s, %(exemplaire_annotationManuscrite)s, %(exemplaire_collator_etatMateriel)s, %(exemplaire_collator_largeur)s, %(exemplaire_reliure_recueilFactice)s, %(exemplaire_reliure_reliure)s, %(exemplaire_reliure_reliureXVI)s, %(exemplaire_relieAvec)s, %(exemplaire_edition_id)s, %(exemplaire_user_id)s, %(exemplaire_bibliothecae_id)s)'] [parameters: {'exemplaire_reliure_reliure': '', 'exemplaire_notes': '', 'exemplaire_provenances': '', 'exemplaire_collator_etatMateriel': '', 'exemplaire_reliure_reliureXVI': 'oui', 'exemplaire_collator_largeur': '', 'exemplaire_pressmark': '', 'exemplaire_stcnFingerprint': '', 'exemplaire_user_id': 1, 'exemplaire_reliure_recueilFactice': 'oui', 'exemplaire_digitalURL': '', 'exemplaire_edition_id': 201899, 'exemplaire_variantesEdition': '', 'exemplaire_bibliothecae_id': '', 'exemplaire_annotationManuscrite': None, 'exemplaire_locFingerprint': '', 'exemplaire_hauteur': '', 'exemplaire_relieAvec': ''}] 
(Background on this error at: http://sqlalche.me/e/gkpj)
[2018-07-10 23:32:05 +0200] [10076] [DEBUG] POST /erasmus/ajout_exemplaire/201899
[2018-07-10 23:32:05 +0200] [10076] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:32:06 +0200] [10076] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:32:13 +0200] [10076] [DEBUG] GET /erasmus/exemplaire/7378
[2018-07-10 23:32:14 +0200] [10076] [DEBUG] GET /erasmus/suppression_exemplaire/7378
[2018-07-10 23:32:16 +0200] [10076] [DEBUG] POST /erasmus/suppression_exemplaire/7378
[2018-07-10 23:32:16 +0200] [10076] [DEBUG] GET /erasmus/edition/201899
[2018-07-10 23:32:16 +0200] [10074] [DEBUG] GET /erasmus/edition/None
[2018-07-10 23:36:59 +0200] [10076] [DEBUG] GET /erasmus/modif_edition/201899

**Comment by MrGecko** [comment]
Le problème est que lors d'un ajout d'exemplaire, on peut sélectionner une bibliothèque 'vide'.
Or le balise <option value=''></option> a pour valeur '' (chaine vide), et donc le champ bibliotheque_id = '' lors de l'enregistrement de l'exemplaire. Mais '' n'est pas un ID de bibliothèque valide, donc la Foreign Key qui joint un exemplaire à une bibliothuqèe n'est pas respectée -> erreur.

Ce qu'il faut donc faire c'est ne pas insérer '' mais **None**, pour signifier qu'il n'y a pas de bibliothèque liée à l'exemplaire. Ainsi la Foreign Key devient valide. 

**donnees.py : ligne  412 :** 
```python
exemplaire_bibliothecae_id=bibliothecae_id if len(bibliothecae_id) > 0 else None,
```

@AnZadykhina  Je vous laisse apporter la modification  ? Merci de ne pas recréer de branche mais de travailler 'derniers_ajouts'.

**Comment by AnZadykhina** [comment]
@MrGecko merci beaucoup pour votre aide. Je rajouterai ces modifications pendant ce week-end. J'ai juste une question : si je comprends bien je dois rajouter cette condition dans ajout et modification d'exemplaire. J'ai le même choix dans autres formulaires (par exemple référence), je la rajoute aussi?

**Comment by MrGecko** [comment]
@AnZadykhina Si dans ces cas il s'agit de jointures entre deux tables (comme ici Exemplaire et Bibliothèque) et que vous avez des listes déroulantes avec un choix vide possible pour lier ces deux tables : oui il faudrait apporter la même modifciation.
La modification à apporter et au fichier donnees.py à la ligne que j'ai signalée.

**Comment by AnZadykhina** [comment]
@MrGecko j'ai rajouté ces modifications dans 3 fonctions (pour exemplaire, citation et référence). J'ai aussi résolu le problème que Mme Bénévent a rencontré. J'espère qu'il n'y aura plus de problème de ce type, j'ai vérifié tous les formulaires, mais il y a beaucoup de champs et c'est possible qu'il reste des coquilles  Si j'ai oublié quelques choses, écrivez-moi, j'essayerai de faire ça plus vite possible.
